version: '3.8'

services:
  minichat:
    build: .
    ports:
      - "3216:3216"

  cors:
    image: redocly/cors-anywhere:latest
    ports:
      - "8080:8080"

  portkey:
    ports:
      - "8787:8787"
    image: "portkeyai/gateway:latest"
    environment:
      PORTKEY_PROVIDER: openai